import { BUILDINGS } from './constants.js';
import { strengthenLink, recordMemory } from './cst.js';
const clamp=(v,lo,hi)=>Math.max(lo,Math.min(hi,v));
function available(state,key){if(Object.prototype.hasOwnProperty.call(state.inventory,key))return state.inventory[key];return state.resources[key]??0;}
function spend(state,key,amount){if(Object.prototype.hasOwnProperty.call(state.inventory,key))state.inventory[key]-=amount;else state.resources[key]=(state.resources[key]??0)-amount;}
export function canAfford(state,type){const def=BUILDINGS[type];if(!def)return false;if(def.tech&&!state.research.unlocked.includes(def.tech))return false;return Object.entries(def.cost).every(([k,v])=>available(state,k)>=v);}
export function getNearestStructure(state,x,y,maxDistance=140){let best=null,bestD=maxDistance;for(const s of state.structures){const d=Math.hypot(s.x-x,s.y-y);if(d<bestD){best=s;bestD=d;}}return best;}
export function placeStructure(state,type,x,y){const def=BUILDINGS[type];if(!def||!canAfford(state,type))return false;if(Math.hypot(x,y)>2350)return false;const overlapping=state.structures.some(s=>Math.hypot(s.x-x,s.y-y)<(BUILDINGS[s.type]?.radius??16)+def.radius-8);if(overlapping)return false;for(const[k,v]of Object.entries(def.cost))spend(state,k,v);const id=`${type}-${state.structures.length}-${Math.round(state.time.elapsed*10).toString(36)}`,nearestSettlement=state.settlements.slice().sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))[0],node={id,type,x,y,health:1,maintenance:1,settlementId:nearestSettlement?.id??null,builtAt:state.time.elapsed},neighbor=getNearestStructure(state,x,y,150);state.structures.push(node);state.stats.built+=1;if(neighbor)strengthenLink(state,node.id,neighbor.id,.12);recordMemory(state,'build',`Constructed ${def.label}`,{id,type,x:Math.round(x),y:Math.round(y)});return true;}
export function createSettlement(state,x,y,name=`Settlement ${state.settlements.length+1}`){const nearbyCore=state.structures.find(s=>s.type==='settlement-core'&&Math.hypot(s.x-x,s.y-y)<80);if(!nearbyCore)return null;const existing=state.settlements.find(s=>Math.hypot(s.x-x,s.y-y)<100);if(existing)return existing;const settlement={id:`settlement-${state.settlements.length}`,name,x,y,health:1};state.settlements.push(settlement);nearbyCore.settlementId=settlement.id;const prior=state.settlements[state.settlements.length-2];if(prior)strengthenLink(state,prior.id,settlement.id,.22);recordMemory(state,'settlement',`Founded ${name}`,{id:settlement.id,x,y});return settlement;}
export function craft(state,recipe){const recipes={'metal-plate':{in:{regolith:3,metal:2},out:{metal:3}},electronics:{in:{silica:2,salvage:2,metal:1},out:{salvage:3}},'oxygen-canister':{in:{ice:2,metal:1},outResource:{oxygen:18}},'water-pack':{in:{ice:3},outResource:{water:12}}},r=recipes[recipe];if(!r||!Object.entries(r.in).every(([k,v])=>available(state,k)>=v))return false;for(const[k,v]of Object.entries(r.in))spend(state,k,v);for(const[k,v]of Object.entries(r.out??{}))state.inventory[k]=(state.inventory[k]??0)+v;for(const[k,v]of Object.entries(r.outResource??{}))state.resources[k]=(state.resources[k]??0)+v;return true;}
export function getNetworkEfficiency(state){if(!state.cst.links.length)return .65;const avg=state.cst.links.reduce((a,l)=>a+l.weight,0)/state.cst.links.length,distancePenalty=state.settlements.length>1?Math.min(.18,(state.settlements.length-1)*.04):0;return clamp(.62+avg*.38-distancePenalty,.35,1.12);}
export function stepProduction(state,dt=1/60){const env=state.environment,eff=getNetworkEfficiency(state);let generation=0,demand=0;for(const s of state.structures){if((s.health??1)<=.05)continue;const def=BUILDINGS[s.type];if(!def)continue;const health=clamp(s.health??1,0,1);if(def.power>0)generation+=(s.type==='solar'?def.power*Math.max(.08,env.solar):def.power)*health;else demand+=-def.power*health;}const net=(generation-demand)*eff,batteryTech=state.research.unlocked.includes('energy-1')?1.5:1;state.resources.powerCapacity=20+state.structures.filter(s=>s.type==='battery').length*22*batteryTech+state.structures.filter(s=>s.type==='reactor').length*30;state.resources.power=clamp(state.resources.power+net*dt*.08,0,state.resources.powerCapacity);const powerFactor=generation+demand>0?clamp((generation+state.resources.power*.12)/(demand||1),.15,1):1,count=type=>state.structures.filter(s=>s.type===type&&(s.health??1)>.2).length,waterUnits=count('water')+count('deep-drill')*1.8;if(waterUnits>0&&state.inventory.ice>0&&powerFactor>.2){const used=Math.min(state.inventory.ice,waterUnits*dt*.035*powerFactor);state.inventory.ice-=used;state.resources.water+=used*2.4*eff;}const oxygenUnits=count('oxygen')+count('greenhouse')*.7;if(oxygenUnits>0&&powerFactor>.2){const feed=Math.min(state.inventory.ice+state.resources.water*.12,oxygenUnits*dt*.035);if(feed>0){const fromIce=Math.min(state.inventory.ice,feed);state.inventory.ice-=fromIce;const remaining=feed-fromIce;state.resources.water=Math.max(0,state.resources.water-remaining*.6);state.resources.oxygen=Math.min(180,state.resources.oxygen+feed*2.8*powerFactor*eff);}}if(count('miner')>0&&powerFactor>.35){const rate=count('miner')*dt*.018*eff;state.inventory.regolith+=rate*1.6;state.inventory.metal+=rate*.45;state.inventory.silica+=rate*.3;}if(count('research')>0&&powerFactor>.35)state.research.points+=count('research')*dt*.007*eff;const stormDamage=state.environment.storm?.type==='dust'?state.environment.storm.severity*.00008*dt:0;for(const s of state.structures){if(stormDamage>0)s.health=clamp((s.health??1)-stormDamage,0,1);s.maintenance=clamp((s.maintenance??1)-.00001*dt,0,1);}return{generation,demand,powerFactor,efficiency:eff};}
