import { BUILDINGS } from './constants.js';
import { projectCinematic, atmosphereProfile } from './visuals.js';

const TAU=Math.PI*2;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const COLORS={habitat:'#d8d0c7',solar:'#5aa9d8',battery:'#c18a42',oxygen:'#83d7c8',water:'#3f97c8',storage:'#9d7352',fabricator:'#d56e4d',relay:'#7ce8ff','rover-bay':'#b98661',research:'#b89af2',radiator:'#ef9d62',shelter:'#8d817a',greenhouse:'#58bb78',reactor:'#ffb348','deep-drill':'#8f6d53',miner:'#c39362','drone-pad':'#75c5d3',uplink:'#e6d58e','cst-relay':'#69f7f0','memory-archive':'#b99aff','lattice-hub':'#ffca62','settlement-core':'#eee9df'};

export class CanvasRenderer{
  constructor(canvas){
    this.canvas=canvas;this.ctx=canvas.getContext('2d');this.camera={x:0,y:0,zoom:1};this.scanSamples=[];this.mic=0;this.time=0;this.resize();globalThis.addEventListener?.('resize',()=>this.resize());
  }
  resize(){const dpr=Math.min(2,globalThis.devicePixelRatio||1),r=this.canvas.getBoundingClientRect();this.width=Math.max(1,r.width);this.height=Math.max(1,r.height);this.canvas.width=Math.floor(this.width*dpr);this.canvas.height=Math.floor(this.height*dpr);this.ctx.setTransform(dpr,0,0,dpr,0,0);}
  worldToScreen(x,y){return projectCinematic({dx:x-this.camera.x,dy:y-this.camera.y,width:this.width,height:this.height,zoom:this.camera.zoom});}
  visualNode(node){if(node?.id==='habitat-0')return{...node,x:(node.x??0)+255,y:(node.y??0)-165};return node;}
  findNode(state,id){const n=state.structures.find(s=>s.id===id)||state.settlements.find(s=>s.id===id);return this.visualNode(n);}
  draw(runtime,{mic=0,reducedMotion=false}={}){
    const {state,world}=runtime,p=state.player,ctx=this.ctx;this.mic=mic;this.time=performance.now()/1000;
    const follow=.08;this.camera.x+=(p.x-this.camera.x)*follow;this.camera.y+=(p.y-this.camera.y)*follow;
    const atm=atmosphereProfile(state.environment);
    ctx.clearRect(0,0,this.width,this.height);
    this.drawSky(state,world,atm);this.drawGround(state,world,atm);this.drawLinks(state);this.drawRocks(world,atm);this.drawStructures(state);this.drawAnomalies(world);this.drawScan();this.drawPlayer(state);
    if(state.environment.storm?.type==='dust')this.drawDust(atm,reducedMotion);
    this.drawPost(atm);
  }
  drawSky(state,world,atm){
    const ctx=this.ctx,h=this.height,w=this.width,horizon=h*.57;
    let g=ctx.createLinearGradient(0,0,0,horizon);g.addColorStop(0,`rgb(${Math.round(28+atm.daylight*42)},${Math.round(12+atm.daylight*18)},${Math.round(9+atm.daylight*12)})`);g.addColorStop(.55,`rgb(${Math.round(91+atm.daylight*78)},${Math.round(37+atm.daylight*46)},${Math.round(22+atm.daylight*30)})`);g.addColorStop(1,`rgb(${Math.round(182+atm.daylight*48)},${Math.round(80+atm.daylight*45)},${Math.round(45+atm.daylight*22)})`);ctx.fillStyle=g;ctx.fillRect(0,0,w,horizon+2);
    const sunX=w*.18,sunY=h*.43,sunR=Math.max(90,w*.09);const rg=ctx.createRadialGradient(sunX,sunY,0,sunX,sunY,sunR);rg.addColorStop(0,`rgba(255,244,218,${.92*atm.sunStrength})`);rg.addColorStop(.18,`rgba(255,198,132,${.55*atm.sunStrength})`);rg.addColorStop(1,'rgba(255,135,70,0)');ctx.fillStyle=rg;ctx.fillRect(sunX-sunR,sunY-sunR,sunR*2,sunR*2);
    for(let layer=0;layer<4;layer++){const base=horizon-layer*26,amp=24+layer*18,step=75-layer*7;ctx.beginPath();ctx.moveTo(0,horizon+80);for(let x=-step;x<=w+step;x+=step){const phase=(x+this.camera.x*(.04+layer*.02))/110+layer*1.7;const y=base-Math.abs(Math.sin(phase)*amp)-Math.abs(Math.sin(phase*.43+2))*amp*.7;ctx.lineTo(x,y);}ctx.lineTo(w,horizon+90);ctx.closePath();ctx.fillStyle=`rgba(${47+layer*12},${24+layer*7},${18+layer*5},${.78-layer*.12})`;ctx.fill();}
    if(atm.haze>.15){const haze=ctx.createLinearGradient(0,horizon*.45,0,horizon+40);haze.addColorStop(0,'rgba(220,105,61,0)');haze.addColorStop(1,`rgba(225,117,64,${atm.haze*.24})`);ctx.fillStyle=haze;ctx.fillRect(0,horizon*.35,w,horizon*.7);}
  }
  drawGround(state,world,atm){
    const ctx=this.ctx,w=this.width,h=this.height,horizon=h*.54;const g=ctx.createLinearGradient(0,horizon,0,h);g.addColorStop(0,'#7b321f');g.addColorStop(.4,'#4e2118');g.addColorStop(1,'#160d0b');ctx.fillStyle=g;ctx.fillRect(0,horizon,w,h-horizon);
    ctx.save();ctx.globalAlpha=.24;for(let i=0;i<42;i++){const y=horizon+(i/42)**1.7*(h-horizon),span=(y-horizon)*1.9,offset=((this.camera.x*.18+i*93)%220)-110;ctx.strokeStyle=i%3===0?'rgba(249,161,103,.16)':'rgba(37,13,9,.32)';ctx.lineWidth=1+(i/42)*2;ctx.beginPath();ctx.moveTo(w*.5-span+offset,y);ctx.lineTo(w*.5+span+offset,y+Math.sin(i)*4);ctx.stroke();}ctx.restore();
    for(let i=0;i<95;i++){const q=((i*71+Math.floor(this.camera.x*.6))%997)/997,x=q*w,y=horizon+(((i*131+Math.floor(this.camera.y*.7))%991)/991)*(h-horizon),r=.7+((i*17)%8);ctx.fillStyle=i%5===0?'rgba(244,133,80,.25)':'rgba(19,7,5,.42)';ctx.beginPath();ctx.ellipse(x,y,r*1.5,r*.55,i,0,TAU);ctx.fill();}
    ctx.save();ctx.globalCompositeOperation='screen';for(let i=0;i<13;i++){const x=((i*197+this.camera.x*.4)%w+w)%w,y=h*.68+((i*83)%180),rw=35+((i*29)%90);const rg=ctx.createLinearGradient(x-rw,y,x+rw,y);rg.addColorStop(0,'rgba(255,137,82,0)');rg.addColorStop(.5,`rgba(255,182,121,${.03+atm.sunStrength*.06})`);rg.addColorStop(1,'rgba(255,137,82,0)');ctx.fillStyle=rg;ctx.fillRect(x-rw,y,rw*2,2);}ctx.restore();
  }
  drawRocks(world){const ctx=this.ctx;for(const r of world.rocks){const s=this.worldToScreen(r.x,r.y);if(s.x<-80||s.y<this.height*.5-50||s.x>this.width+80||s.y>this.height+70)continue;const rr=clamp(r.radius*s.scale*.75,2,22);ctx.save();ctx.translate(s.x,s.y);ctx.fillStyle='rgba(0,0,0,.34)';ctx.beginPath();ctx.ellipse(rr*.35,rr*.5,rr*1.1,rr*.32,0,0,TAU);ctx.fill();const g=ctx.createLinearGradient(-rr,-rr,rr,rr);g.addColorStop(0,`rgb(${112+Math.round(r.shade*35)},${58+Math.round(r.shade*20)},${38+Math.round(r.shade*13)})`);g.addColorStop(1,'#2c1510');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(-rr,rr*.2);ctx.lineTo(-rr*.55,-rr*.55);ctx.lineTo(rr*.12,-rr);ctx.lineTo(rr*.82,-rr*.3);ctx.lineTo(rr,rr*.45);ctx.closePath();ctx.fill();ctx.restore();}}
  drawLinks(state){const ctx=this.ctx;ctx.save();ctx.globalCompositeOperation='lighter';for(const l of state.cst.links){const a=this.findNode(state,l.a),b=this.findNode(state,l.b);if(!a||!b)continue;const A=this.worldToScreen(a.x,a.y),B=this.worldToScreen(b.x,b.y);ctx.strokeStyle=`rgba(83,239,236,${.06+l.weight*.48})`;ctx.lineWidth=1+l.weight*3;ctx.shadowColor='#66fff7';ctx.shadowBlur=8*l.weight;ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.stroke();}ctx.restore();}
  drawStructures(state){const nodes=state.structures.map(s=>this.visualNode(s)).map(s=>({s,p:this.worldToScreen(s.x,s.y)})).sort((a,b)=>a.p.y-b.p.y);for(const {s,p} of nodes){if(p.x<-120||p.y<this.height*.45-80||p.x>this.width+120||p.y>this.height+100)continue;if(s.type==='habitat')this.drawHabitat(s,p);else if(s.type==='solar')this.drawSolar(s,p);else if(['relay','cst-relay','uplink'].includes(s.type))this.drawRelay(s,p);else this.drawModule(s,p);}}
  drawHabitat(b,p){const ctx=this.ctx,sc=clamp(p.scale,0.65,1.25),w=170*sc,h=62*sc;ctx.save();ctx.translate(p.x,p.y);ctx.globalAlpha=.6+.4*(b.health??1);ctx.fillStyle='rgba(0,0,0,.42)';ctx.beginPath();ctx.ellipse(10,24*sc,w*.62,18*sc,0,0,TAU);ctx.fill();const g=ctx.createLinearGradient(-w/2,-h/2,w/2,h/2);g.addColorStop(0,'#e5ddd3');g.addColorStop(.35,'#b7aaa0');g.addColorStop(.72,'#62534c');g.addColorStop(1,'#2b2320');ctx.fillStyle=g;ctx.strokeStyle='rgba(255,235,220,.5)';ctx.lineWidth=1.5;roundRect(ctx,-w/2,-h,w,h,25*sc);ctx.fill();ctx.stroke();ctx.fillStyle='#201816';roundRect(ctx,-w*.36,-h*.82,w*.12,h*.6,8*sc);ctx.fill();ctx.fillStyle='#70e9ff';ctx.shadowColor='#70e9ff';ctx.shadowBlur=10;ctx.fillRect(w*.1,-h*.68,w*.32,4*sc);ctx.shadowBlur=0;ctx.fillStyle='#d8c5b9';ctx.fillRect(-w*.39,-h*.15,-30*sc,4*sc);ctx.fillRect(-w*.39,-h*.11,-38*sc,4*sc);ctx.fillStyle='rgba(255,255,255,.72)';ctx.font=`${Math.max(9,11*sc)}px system-ui`;ctx.textAlign='center';ctx.fillText('HAB-01 · RED GENESIS',0,-h*.18);this.marker(ctx,'Habitat',0,-h-20*sc,'#8beeff');ctx.restore();}
  drawSolar(b,p){const ctx=this.ctx,sc=clamp(p.scale,.55,1.2);ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle='rgba(0,0,0,.38)';ctx.beginPath();ctx.ellipse(6,8,45*sc,10*sc,0,0,TAU);ctx.fill();ctx.rotate(-.08);ctx.fillStyle='#173552';ctx.strokeStyle='#73cfff';ctx.lineWidth=1;ctx.fillRect(-42*sc,-19*sc,84*sc,31*sc);for(let x=-30;x<42;x+=15){ctx.beginPath();ctx.moveTo(x*sc,-19*sc);ctx.lineTo(x*sc,12*sc);ctx.stroke();}for(let y=-9;y<12;y+=10){ctx.beginPath();ctx.moveTo(-42*sc,y*sc);ctx.lineTo(42*sc,y*sc);ctx.stroke();}ctx.strokeStyle='#b9c5c8';ctx.beginPath();ctx.moveTo(-15*sc,12*sc);ctx.lineTo(-7*sc,26*sc);ctx.moveTo(15*sc,12*sc);ctx.lineTo(7*sc,26*sc);ctx.stroke();this.marker(ctx,'Solar Array',0,-34*sc,'#78d7ff');ctx.restore();}
  drawRelay(b,p){const ctx=this.ctx,sc=clamp(p.scale,.55,1.25);ctx.save();ctx.translate(p.x,p.y);ctx.strokeStyle=b.type==='cst-relay'?'#74fff5':'#d7c2af';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-13*sc,0);ctx.lineTo(0,-76*sc);ctx.lineTo(13*sc,0);ctx.moveTo(-9*sc,-22*sc);ctx.lineTo(9*sc,-22*sc);ctx.moveTo(-6*sc,-44*sc);ctx.lineTo(6*sc,-44*sc);ctx.stroke();ctx.fillStyle='#ff5b43';ctx.shadowColor='#ff6048';ctx.shadowBlur=15;ctx.beginPath();ctx.arc(0,-79*sc,3.4*sc,0,TAU);ctx.fill();ctx.shadowBlur=0;this.marker(ctx,b.type==='cst-relay'?'CST Relay':'Comm Relay',0,-96*sc,b.type==='cst-relay'?'#77fff6':'#ffd08a');ctx.restore();}
  drawModule(b,p){const ctx=this.ctx,def=BUILDINGS[b.type]??{label:b.type},sc=clamp(p.scale,.55,1.2),r=18*sc;ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle='rgba(0,0,0,.36)';ctx.beginPath();ctx.ellipse(3,8,r*1.2,r*.4,0,0,TAU);ctx.fill();const g=ctx.createLinearGradient(-r,-r,r,r);g.addColorStop(0,COLORS[b.type]??'#c8b8aa');g.addColorStop(1,'#3a2921');ctx.fillStyle=g;ctx.strokeStyle='rgba(255,255,255,.28)';roundRect(ctx,-r,-r*.7,r*2,r*1.4,6*sc);ctx.fill();ctx.stroke();this.marker(ctx,def.label,0,-r-12*sc,COLORS[b.type]??'#eee');ctx.restore();}
  marker(ctx,label,x,y,color){ctx.save();ctx.textAlign='center';ctx.font='700 10px system-ui';ctx.fillStyle=color;ctx.shadowColor='rgba(0,0,0,.8)';ctx.shadowBlur=5;ctx.fillText(label,x,y);ctx.strokeStyle=color;ctx.globalAlpha=.55;ctx.beginPath();ctx.moveTo(x,y+4);ctx.lineTo(x,y+18);ctx.stroke();ctx.restore();}
  drawAnomalies(world){const ctx=this.ctx;for(const a of world.anomalies){if(!a.discovered)continue;const s=this.worldToScreen(a.x,a.y),pulse=7+Math.sin(this.time*3+a.x)*2+this.mic*8;ctx.strokeStyle='rgba(174,124,255,.82)';ctx.lineWidth=1.5;ctx.shadowColor='#aa7bff';ctx.shadowBlur=12;ctx.beginPath();ctx.arc(s.x,s.y,pulse,0,TAU);ctx.stroke();ctx.shadowBlur=0;}}
  drawScan(){const ctx=this.ctx;for(const v of this.scanSamples){const s=this.worldToScreen(v.x,v.y),color=v.type==='ice'?'#5ee8ff':v.type==='anomaly'?'#c48cff':'#ffbd61';ctx.fillStyle=color;ctx.shadowColor=color;ctx.shadowBlur=16;ctx.beginPath();ctx.arc(s.x,s.y,3+v.richness*5,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,255,255,.45)';ctx.beginPath();ctx.arc(s.x,s.y,12+v.richness*5,0,TAU);ctx.stroke();}}
  drawPlayer(state){const p=state.player,s=this.worldToScreen(p.x,p.y-p.altitude*2.4),ctx=this.ctx;if(p.mode==='rover')return this.drawRover(p,s);ctx.save();ctx.translate(s.x,s.y);ctx.fillStyle='rgba(0,0,0,.4)';ctx.beginPath();ctx.ellipse(8,27,26,8,0,0,TAU);ctx.fill();ctx.rotate(p.facing*.18);ctx.fillStyle='#4e2017';roundRect(ctx,-15,-22,30,48,11);ctx.fill();ctx.fillStyle='#ded4ca';roundRect(ctx,-14,-18,28,38,10);ctx.fill();ctx.fillStyle='#5c241a';ctx.fillRect(-15,-2,7,16);ctx.fillRect(8,-2,7,16);ctx.fillStyle='#242b31';ctx.beginPath();ctx.arc(0,-25,14,0,TAU);ctx.fill();const visor=ctx.createLinearGradient(-10,-30,10,-20);visor.addColorStop(0,'#7ceaff');visor.addColorStop(.5,'#233743');visor.addColorStop(1,'#f49b6a');ctx.fillStyle=visor;ctx.beginPath();ctx.arc(0,-25,10,Math.PI*.95,Math.PI*2.05);ctx.fill();ctx.fillStyle='#a89b8f';roundRect(ctx,-23,-12,10,29,4);ctx.fill();ctx.fillStyle='#69eff0';ctx.shadowColor='#69eff0';ctx.shadowBlur=10;ctx.fillRect(-21,9,6,2);ctx.shadowBlur=0;ctx.strokeStyle='#d8cfc6';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-8,17);ctx.lineTo(-13,31);ctx.moveTo(8,17);ctx.lineTo(13,31);ctx.stroke();ctx.restore();}
  drawRover(p,s){const ctx=this.ctx;ctx.save();ctx.translate(s.x,s.y);ctx.rotate(p.facing*.15);ctx.fillStyle='rgba(0,0,0,.42)';ctx.beginPath();ctx.ellipse(3,20,38,10,0,0,TAU);ctx.fill();ctx.fillStyle='#161616';for(const x of[-26,21])for(const y of[-10,12]){ctx.beginPath();ctx.arc(x,y,9,0,TAU);ctx.fill();}const g=ctx.createLinearGradient(-30,-12,32,15);g.addColorStop(0,'#d7cec2');g.addColorStop(.55,'#8b766a');g.addColorStop(1,'#372820');ctx.fillStyle=g;roundRect(ctx,-33,-14,66,28,10);ctx.fill();ctx.fillStyle='#1c343f';roundRect(ctx,2,-9,24,14,4);ctx.fill();ctx.fillStyle='#65e7ff';ctx.shadowColor='#65e7ff';ctx.shadowBlur=11;ctx.fillRect(6,-6,16,3);ctx.shadowBlur=0;ctx.fillStyle='#d06243';ctx.fillRect(-25,-8,10,16);ctx.restore();}
  drawDust(atm,reduced){const ctx=this.ctx,w=this.width,h=this.height;ctx.fillStyle=`rgba(165,72,35,${atm.dustOpacity})`;ctx.fillRect(0,0,w,h);if(reduced)return;ctx.save();ctx.strokeStyle=`rgba(255,186,125,${.08+atm.stormSeverity*.18})`;ctx.lineWidth=1.2;for(let i=0;i<95;i++){const y=(i*43+this.time*120)%h,x=(i*109+this.time*260)%w,len=20+atm.stormSeverity*55;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+len,y-5);ctx.stroke();}ctx.restore();}
  drawPost(atm){const ctx=this.ctx,w=this.width,h=this.height;const vignette=ctx.createRadialGradient(w*.5,h*.5,Math.min(w,h)*.2,w*.5,h*.5,Math.max(w,h)*.72);vignette.addColorStop(.55,'rgba(0,0,0,0)');vignette.addColorStop(1,'rgba(0,0,0,.52)');ctx.fillStyle=vignette;ctx.fillRect(0,0,w,h);ctx.fillStyle=`rgba(255,116,62,${atm.haze*.045})`;ctx.fillRect(0,0,w,h);}
}
function roundRect(ctx,x,y,w,h,r){if(ctx.roundRect){ctx.beginPath();ctx.roundRect(x,y,w,h,r);return;}ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath();}
